version: '3.8'

services:
  eureka-server:
    image: eureka-server-image
    networks:
      - eureka-network
    container_name: eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    ports:
      - "8761:8761"

  api-gateway:
    image: api-gateway-image
    networks:
      - eureka-network
    container_name: api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  question-anwser:
    image: question-anwser-image:latest
    networks:
      - eureka-network
    container_name: question-anwser
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

    ports:
      - "8088:8088"
    depends_on:
      - eureka-server

  notification:
    image:  notification-image
    networks:
      - eureka-network
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
  analytics:
    image: analytics-image
    networks:
      - eureka-network
    container_name: analytics-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server

  postgres:
    image: postgres
    networks:
      - eureka-network
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vermeg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
networks:
  eureka-network:
    driver: bridge